### PR TITLE
Drop object-path

### PR DESCRIPTION
**Pull request by TrySound**
Ref https://github.com/bholloway/adjust-sourcemap-loader/issues/16

A good reason to drop this package since it's not used for any magic and
the fix is pretty straightforward. Later can be simplified with optional
chaining syntax.

### CODE REVIEW

**Comment by TrySound** [comment]
cc @bholloway

**Comment by TrySound** [comment]
Hi @bholloway Is it ready for release?

**Comment by peteroruba** [comment]
We're also eagerly waiting for a new release with this change.

**Comment by nayaks2019** [comment]
Please Release the latest code which has fix for object-path

**Comment by justinhamadeunity** [comment]
Hi @bholloway looks like a new version probably 2.0.1 needs to be released to NPM still?  Thanks.

**Pull request merged**
